#   ____
#  / ___|___  _ __ ___
# | |   / _ \| '__/ _ \
# | |__| (_) | | |  __/
#  \____\___/|_|  \___|
#
FROM pandoc/minimal:${pandoc_version}-alpine

# Additional packages frequently used during conversions
# hadolint ignore=DL3018
RUN apk --no-cache add rsvg-convert

# Install pandoc-crossref
RUN <<EOF
set -eux
apk --no-cache add curl
url_base='https://github.com/lierdakil/pandoc-crossref/releases/download';
case "$$(uname -m)" in
    ('x86_64')
        arch="X64"
        crossref_hash=${core.pandoc-crossref.hashes.amd64}
        ;;
    ('aarch64')
        arch="ARM64"
        crossref_hash=${core.pandoc-crossref.hashes.arm64}
        ;;
    (*)
        echo >&2 "error: unsupported architecture '$$(uname -m)'"
        exit 1
        ;;
esac
version="${core.pandoc-crossref.version}"
filename="pandoc-crossref-Linux-$${arch}.tar.xz"
curl --proto '=https' --tlsv1.3 -sSfL -o /tmp/pandoc-crossref.tar.xz \
    "$${url_base}/$${version}/pandoc-crossref-linux-$${arch}.tar.xz"
echo "$$crossref_hash /tmp/pandoc-crossref.tar.xz" | sha256sum -c
tar -xf /tmp/pandoc-crossref.tar.xz -C /usr/local/bin pandoc-crossref
# Remove archive
rm /tmp/pandoc-crossref.tar.xz
# Curl is no longer needed
apk del curl
EOF

