#  _         _____   __  __
# | |    __ |_   _|__\ \/ /
# | |   / _` || |/ _ \\  /
# | |__| (_| || |  __//  \
# |_____\__,_||_|\___/_/\_\
#
FROM pandoc/core:${pandoc_version}-alpine

# NOTE: to maintainers, please keep this listing alphabetical.
RUN apk --no-cache add \
        curl \
        fontconfig \
        freetype \
        gnupg \
        gzip \
        perl \
        tar \
        wget \
        xz

# Installer config
COPY <<EOF /root/texlive.profile
$addon.latex.texlive.profile$
EOF

# TeXLive binaries location
ARG texlive_bin="/opt/texlive/texdir/bin"

# TeXLive mirror URL (leave empty to use the default mirror).
$if(addon.latex.current-texlive)$
ARG texlive_mirror_url=
$else$
ARG texlive_mirror_url="ftp://tug.org/historic/"
$endif$

# Modify PATH environment variable, prepending TexLive bin directory
ENV PATH="$${texlive_bin}/default:$${PATH}"

# Ideally, the image would always install "linuxmusl" binaries. However,
# those are not available for aarch64, so we install binaries that have
# been built against libc and hope that the compatibility layer works
# well enough.
RUN <<EOF
set -eux
cd /root
ARCH="$$(uname -m)"
case "$$ARCH" in
    ('x86_64') TEXLIVE_ARCH="x86_64-linuxmusl"
        ;;
    (*) echo >&2 "error: unsupported architecture '$$ARCH'";
        exit 1
        ;;
esac
mkdir -p $${texlive_bin}
ln -sf "$${texlive_bin}/$${TEXLIVE_ARCH}" "$${texlive_bin}/default"
# Request musl precompiled binary access
echo "binary_$${TEXLIVE_ARCH} 1" >> /root/texlive.profile

# Install TeXLive
mirror_url="${texlive_mirror_url}"

if [ -z "$${mirror_url}" ]; then
    # Get the mirror URL from the redirect. Otherwise, if we were to
    # always use the mirror URL, we'd run into problems whenever we get
    # installer and signatures from different mirrors that are not 100%
    # in sync.
    mirror_url=$$(wget -4 --quiet --output-document=/dev/null \
                      --server-response \
                      http://mirror.ctan.org/ \
                      2>&1 | \
                      sed -ne 's/.*Location: \(.*\)$$/\1/p' | head -n 1)
fi

# Trim trailing slash(es)
mirror_url=$$(echo "$$mirror_url" | sed -e 's/\/*$$//')

$if(addon.latex.texlive.is-current)$
installer_url="$${mirror_url}/systems/texlive/tlnet"
$else$
installer_url="$${mirror_url}/systems/texlive/${addon.latex.texlive.version}/tlnet-final"
$endif$

# Download the install-tl perl script. The archive integrity and signature is
# verified later, so it's ok if we use an insecure connection.
wget -4 --no-verbose --no-check-certificate \
    "$$installer_url/install-tl-unx.tar.gz" \
    "$$installer_url/install-tl-unx.tar.gz".sha512 \
    "$$installer_url/install-tl-unx.tar.gz".sha512.asc \

## Verifiy installer integrity
# get current signing key
gpg --keyserver keyserver.ubuntu.com \
    --receive-key 0xC78B82D8C79512F79CC0D7C80D5E5D9106BAB6BC || exit 5
gpg --verify install-tl-unx.tar.gz.sha512.asc || exit 5
sha512sum install-tl-unx.tar.gz.sha512 || exit 5

## Proceed with installation
# Extract installer
mkdir -p ./install-tl
tar --strip-components 1 -zvxf install-tl-unx.tar.gz -C "$$PWD/install-tl"

# Run the default installation with the specified profile.
./install-tl/install-tl \
    -repository "$${installer_url}" \
    --profile=/root/texlive.profile

# Cleanup installation artifacts.
rm -rf \
    ./install-tl \
    install-tl-unx.tar.gz \
    install-tl-unx.tar.gz.sha512 \
    install-tl-unx.tar.gz.sha512.asc

# Install packages required by pandoc
tlmgr install \
    --verify-repo=all \
$for(addon.latex.packages)$
    ${it}$sep$ \
$endfor$

# Reset to the default CTAN mirror, unless a specific mirror had been
# requested.
if [ -z "$${texlive_mirror_url}" ]; then
    tlmgr option repository ctan
fi

rm -f /root/texlive.profile

# Update fonts
TERM=dumb luaotfload-tool --update && \
chmod -R o+w /opt/texlive/texdir/texmf-var
EOF
