#   ____
#  / ___|___  _ __ ___
# | |   / _ \| '__/ _ \
# | |__| (_) | | |  __/
#  \____\___/|_|  \___|
#
FROM pandoc/minimal:${pandoc_version}-debian

# Additional packages frequently used during conversions
# NOTE: `libsrvg`, pandoc uses `rsvg-convert` for working with svg images.
RUN apt-get -q --no-allow-insecure-repositories update \
  && DEBIAN_FRONTEND=noninteractive \
     apt-get install --assume-yes --no-install-recommends \
       librsvg2-bin=2.* \
  && rm -rf /var/lib/apt/lists/*

# Install pandoc-crossref
RUN <<EOF
set -eux

# Install curl
apt-get -q --no-allow-insecure-repositories update
apt-get install --assume-yes --no-install-recommends --mark-auto curl xz-utils

url_base='https://github.com/lierdakil/pandoc-crossref/releases/download';
case "$$(uname -m)" in
    ('x86_64')
        arch="X64"
        crossref_hash=${core.pandoc-crossref.hashes.amd64}
        ;;
    ('aarch64')
        arch="ARM64"
        crossref_hash=${core.pandoc-crossref.hashes.arm64}
        ;;
    (*)
        echo >&2 "error: unsupported architecture '$$(uname -m)'"
        exit 1
        ;;
esac
version="${core.pandoc-crossref.version}"
filename="pandoc-crossref-Linux-$${arch}.tar.xz"
curl --proto '=https' --tlsv1.3 -sSfL -o /tmp/pandoc-crossref.tar.xz \
    "$${url_base}/$${version}/pandoc-crossref-linux-$${arch}.tar.xz"
echo "$$crossref_hash /tmp/pandoc-crossref.tar.xz" | sha256sum -c
tar -xf /tmp/pandoc-crossref.tar.xz -C /usr/local/bin pandoc-crossref
# Remove archive
rm /tmp/pandoc-crossref.tar.xz
# Curl is no longer needed
apt-get autoremove --purge --assume-yes; \
rm -rf /var/lib/apt/lists/*;
EOF

