name: Image Builder

on:
  push:
    paths:
      - 'debian/*'
      - 'versions.md'
      - 'LICENSE'
      - '**/bookworm/*'
  pull_request:
    # Build, but don't push on pull requests

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: configure

    strategy:
      fail-fast: false
      matrix:
        stack: ${{ fromJSON( needs.configure.outputs.stacks ) }}
        version: ${{ fromJSON( needs.configure.outputs.pandoc-version ) }}

    env:
      PUSH_IMAGE: ${{ github.repository == 'pandoc/dockerfiles' &&
                      (github.ref == 'refs/heads/main' ||
                       github.ref_type == 'tag' ||
                       github.event_name != 'pull_request') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.PUSH_IMAGE }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and maybe push image
        uses: docker/build-push-action@v5
        with:
          file: '3.5/bookworm/Dockerfile'
          context: '.'
          push: ${{ env.PUSH_IMAGE }}
          tags: '3.5-debian'
