name: Image Builder

on:
  push:
  pull_request:
    # Build, but don't push on pull requests

jobs:
  build:
    name: Debian
    runs-on: ubuntu-latest

    env:
      PUSH_IMAGE: ${{ github.repository == 'pandoc/dockerfiles' &&
                      (github.ref == 'refs/heads/main' ||
                       github.ref_type == 'tag' ||
                       github.event_name != 'pull_request') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.PUSH_IMAGE }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and maybe push image
        uses: docker/build-push-action@v5
        with:
          file: '3.5/bookworm/Dockerfile'
          context: '.'
          platforms: linux/arm64/v8
          push: ${{ env.PUSH_IMAGE }}
          tags: 'pandoc/core:3.5-debian'
