name: Meta

on:
  workflow_call:
    inputs:
      images:
        type: string
        required: true
      pandoc_version:
        type: string
        default: main
      build_stack:
        type: string
        default: alpine

jobs:
  conf:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      base_image: ${{ steps.config.outputs.base_image }}
      base_image_version: ${{ steps.config.outputs.base_image_version }}
      build_stack: ${{ steps.config.outputs.build_stack }}
      labels: ${{ steps.meta.outputs.labels }}
      tags: ${{ steps.config.outputs.tags }}
      texlive_version: ${{ steps.config.outputs.texlive_version }}

    steps:
      - name: Config
        id: config
        run: |
          ./scripts/config.sh \
              ${{ inputs.pandoc_version }} \
              ${{ inputs.build_stack }} \
              ${{ inputs.images }}
          ./scripts/config.sh \
              ${{ inputs.pandoc_version }} \
              ${{ inputs.build_stack }} \
              ${{ inputs.images }} \
              >> $GITHUB_OUTPUT

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.images }}
